### ISSUE TITLE
Details about quantitative evaluation results on other models

### ISSUE THREAD

**Issue by LeoJoy39** [YxZhxn/Ray3D#10]
Hi, thanks for the great work.
I want to know whether you used the camera intrinsic and extrinsic parameters when you did quantitative evaluation on other models(PoseFormer, VideoPose, RIE), or you just used their original code(without using the camera intrinsic and extrinsic parameters imformation, in other words, you didn't mapping the inputs and outputs to NCS) for quantitative evaluation comparison?

**Comment by YxZhxn** [comment]
Our Ray3D design can be easily incorporated to the existing pose estimation framework. During quantitative evaluation, we integrate Ray3D with RIE and VideoPose and compare with vanilla VideoPose, PoseFormer and RIE.

**Comment by LeoJoy39** [comment]
Thanks for your reply!
Another question, when you did generalization experiments, how did you get the synthetic inputs_2d and inputs_3d data for  vanilla VideoPose, PoseFormer and RIE evaluations?

**Comment by YxZhxn** [comment]
The synthetic data we generated contain inputs_2d and inputs_3d with no Ray3D encoding, you can use them directly for vanilla VideoPose, PoseFormer and RIE evaluations.

**Comment by LeoJoy39** [comment]
You generated 324 virtual cameras for training, that means you did at least 324*5 (for models: PoseFormer, RIE, VideoPose, Ray3D and  Ray3D_w/o_CE) times training for generalization evaluations (that is heavy workload)?

**Comment by YxZhxn** [comment]
Yes, but we reimplemented the training logic on synthetic branch to speed up training.

**Comment by LeoJoy39** [comment]
> The synthetic data we generated contain inputs_2d and inputs_3d with no Ray3D encoding, you can use them directly for vanilla VideoPose, PoseFormer and RIE evaluations.

When you evaluated on vanilla VideoPose, PoseFormer and RIE, the inputs_2d and inputs_3d(gt_3d) were in which coordinate system? (We usually map the gt_3d to CCS and the inputs_2d is in pixel coordinate system (maybe do screen coordinates normalization) in root relative 3D pose estimation tasks) Can I understand the Ray3D encoding as mapping both the inputs_2d  and inputs_3d from CCS to NCS ?

**Comment by YxZhxn** [comment]
All model's performance are evaluated in WCS. For vanilla VideoPose, PoseFormer and RIE, inputs_2d is in pixel coordinate system, inputs_3d is in CCS. For Ray3D, inputs_2d and inputs_3d are in NCS. Since we have camera intrinsics and extrinsics, all prediction can be transformed to WCS correspondingly.
