### ISSUE TITLE
Why do I use the extrinsic and extrinsic parameters of the camera to train the model?

### ISSUE THREAD

**Issue by DryPilgrim** [YxZhxn/Ray3D#11]
If I know the camera's intrinsic and extrinsic parameters, I can directly compute  the 3D coordinates?

**Comment by YxZhxn** [comment]
Yes. When provided with multi-view cameras including intrinsics and extrinsics, one can estimate 3D coordinates with triangulation. However, 3D coordinate estimation is still ill-posed with single monocular camera.
