### ISSUE TITLE
question

### ISSUE THREAD

**Issue by faggots2** [YxZhxn/Ray3D#12]
FileNotFoundError: [Errno 2] No such file or directory: 'D:/浏览器/IE下载/SPIN-master/datasets/preprocess/mpi_inf_3dhp\\S1\\Seq1\\annot.mat'
Why is this problem
Why should a suffix be added after it? What is the function of the suffix

**Comment by YxZhxn** [comment]
Please explain your problem more specifically. I notice that you are using data from SPIN. I believe that it is not related to the Ray3D repository. You have to figure it out by yourself.
