### ISSUE TITLE
相机augmentation的问题

### ISSUE THREAD

**Issue by pmj110119** [YxZhxn/Ray3D#13]
大佬好！

在论文附录中有对Human3.6M的相机内参、外参分别做了augmentation，生成多个“虚拟相机”。 请问下这一步具体是怎么做的呢？

我查了下Human3.6M并不是合成数据集，如何生成相机外参aug（比如说旋转后）的图像呢？

**Comment by YxZhxn** [comment]
1）虚拟相机的生成方式可以在readme里面查看到，包括对内参和外参的扰动。

**Comment by YxZhxn** [comment]
1）虚拟相机的生成可以参考readme里面的相关步骤，主要包括两部分。比较粗暴地去调整原有相机的内外参。
<img width="872" alt="Screen Shot 2022-07-07 at 17 31 28" src="https://user-images.githubusercontent.com/48275694/177742344-c79b4868-6ae4-4a84-bc36-60bd099c28c7.png">
2）我们没有生成虚拟相机下的图像，只是依照新生成的相机参数和原有3D关键点计算得到虚拟视角下的2D骨骼用于训练和测试。
