### ISSUE TITLE
运行单个视频的问题

### ISSUE THREAD

**Issue by YCBjust** [YxZhxn/Ray3D#14]
您好，请问可以发布一个简单运行的方式吗？ 比如我要用这个模型运行一段视频或者说是图片。
 python test.py  xxx/xx.jpg（xxx.avi）这个样子的。
然后返回关键点的3D绝对位置。
麻烦了

**Comment by YxZhxn** [comment]
你可以参考这个issue #8 里面的回答以及相关的链接来准备测试数据。需要提供给Ray3D的输入有相机内外参数，2D骨骼点序列。

**Comment by YCBjust** [comment]
非常感谢
