### ISSUE TITLE
when use in wild videos, what affect its performance?

### ISSUE THREAD

**Issue by linyu0219** [YxZhxn/Ray3D#15]
Great works first!
I make a h36m-like custom data. And I use the h36m pretrained model, but the result is not good.
![ray3dh36m](https://user-images.githubusercontent.com/29172715/178919851-f2a51c01-e2ce-486f-8214-1977cd7f7f01.png)
I have some questions.
1.Does h36m with aug will better ? Or other datasets pretrained model performance good for wild video?
2.When we use in the wild, what procedure do you recommend?
For example,
Use custom database train. Use same camera record video  which has a intrinsic params when inference.

**Comment by YxZhxn** [comment]
To answer your questions:

1. The camera embedding module in vanilla h36m pretrained model is trained with original 4 cameras, which means that camera embedding module has little generalization to other camera setting. h36m with augmentation will gives you better prediction. If there are other pretrained models share similar camera parameters with your custom dataset. They will also perform better.  
2. For those in-the-wild scenarios, once you have rough estimated camera parameters, a small scale training or fine-tuning at first is recommended.

**Comment by mnauf** [comment]
Do we have "h36m with aug" model? @YxZhxn @linyu0219

**Comment by YxZhxn** [comment]
"h36m with aug" model is not released. You can train it by yourself once you have the augmented data.
