### ISSUE TITLE
error results on pretrained model

### ISSUE THREAD

**Issue by JihuaPeng** [YxZhxn/Ray3D#16]
I have downloaded your pretrained model, but it generated error results when i run the code to evaluate it. Can you tell me the reason？Thanks a lot!
![image](https://user-images.githubusercontent.com/30943144/191543555-ed5e72fe-d8a6-4bff-8163-7c63cc22a946.png)

**Comment by YxZhxn** [comment]
It seems that you accidentally used either the incorrect configuration or the mismatch pretrained model. Without more details, i cannot give you possible cause precisely. Anyway, you can debug it by yourself.
