### ISSUE TITLE
关于预训练模型预测时结果错误的问题

### ISSUE THREAD

**Issue by MingjieWe** [YxZhxn/Ray3D#17]
大佬您好！非常感谢您所做的杰出工作。我想请问一下，我下载您在ReadMe中的预训练模型和数据集后，在测试时发现预测结果相差很大，请问是什么情况。谢谢大佬！
![图片](https://user-images.githubusercontent.com/49791893/203049543-7af39a18-b89d-454c-8bc1-b10db7f3cc99.png)
对于checkpoint/RAY3DRIEX_h36m_3_RIE_FRAME9_LR0.0005_EPOCH20_BATCH1024_Oct_31_2021_05_43_36/configs/data_config.json文件的配置：
`{
    "DATASET": "h36m",
    "WORLD_3D_GT_EVAL": true,
    "KEYPOINTS": "gt",
    "TRAIN_SUBJECTS": "S1,S5,S6,S7,S8",
    "TEST_SUBJECTS": "S9,S11",
    "GT_3D": "E:/HPE/Ray3D-main/Ray3D-main/dataset/data_3d_h36m.npz",
    "GT_2D": "E:/HPE/Ray3D-main/Ray3D-main/dataset/data_2d_h36m_gt.npz",
    "CAMERA_PARAM": "",
    "SUBSET": 1,
    "STRIDE": 1,
    "DOWNSAMPLE": 1,
    "ACTIONS": "*",
    "REMOVE_IRRELEVANT_KPTS": false,
    "FRAME_PATH": "/ssd/yzhan/data/benchmark/3D/showroom/20210702/frame/",
    "INTRINSIC_ENCODING": false,
    "RAY_ENCODING": true
}
`
对于cfg文件夹下的文件路径也做了相应的调整后，仍然未解决该问题。

**Comment by YxZhxn** [comment]
你可以确认一下预训练权重是否被正确加载, 之前有用户碰见和你类似的问题. 经反馈原因是在cpu模式下加载gpu权重失败导致的.

**Comment by MingjieWe** [comment]
非常感谢您提供的帮助，问题已经解决了，谢谢！

**Comment by YxZhxn** [comment]
可以分享一下导致你上述问题的原因吗? 方便其他有类似问题的人可以通过查看这个issue解决同样的问题,谢谢.

**Comment by MingjieWe** [comment]
该问题解决方法是：将lib/train_val/trainer.py文件中的evaluate_core函数在运行时需要确保已经加载了可以使用的gpu。
因为预训练权重是gpu权重，所以需要将输入数据转移至cuda上。
