### ISSUE TITLE
Predictions wont visualize, only GTs do

### ISSUE THREAD

**Issue by mnauf** [YxZhxn/Ray3D#18]
Thanks for your great work! The code is visualizing the ground truths but not the predictions and the input image. What am I missing? I am running the main branch, and using the eva dataset. I get in the logs "MovieWriter imagemagick unavailable". I have also tried by using ffmpeg, but same results in mp4 video.
![eva](https://user-images.githubusercontent.com/41832069/218128139-d436ddb6-b231-4a83-a213-feeb8b76c238.gif)

**Comment by YxZhxn** [comment]
Hi! You can dig into the code written in visualization.py and check the data right before drawing them on the canvas. Make sure everything is loaded correctly.

**Comment by mnauf** [comment]
Now I am running the same command as suggested for visualization with the same config and checkpoint. It's predicting random keypoints far away from GT. The reason why it doesn't show images is, I don't have human3.6m videos.

```
python3 main.py \
    --cfg cfg_ray3d_h36m_stage3 \
    --timestamp Oct_31_2021_05_43_36 \
    --evaluate best_epoch.bin \
    --render
```

How can I fix this? Same is the case when I tried with humaneva dataset and their corresponding models and config files. Maybe [this issue](https://github.com/YxZhxn/Ray3D/issues/16) addressed the same.

I have only made 2 changes:

1- `Ray3D\checkpoint\RAY3DRIEX_h36m_3_RIE_FRAME9_LR0.0005_EPOCH20_BATCH1024_Oct_31_2021_05_43_36\configs\data_config.json`: changed path of 2D and 3D GTs.

2- `Ray3D\cfg\cfg_ray3d_h36m_stage3.py`: Changed path of 2D and 3D Gts in the data_config dictionary.

![debug](https://user-images.githubusercontent.com/41832069/218401031-67297461-3486-45ee-89ff-7680d7167d32.png)

**Comment by mnauf** [comment]
Solved.  Change `"DEVICE": "4,5"` in `Ray3D\checkpoint\RAY3DRIEX_h36m_3_RIE_FRAME9_LR0.0005_EPOCH20_BATCH1024_Oct_31_2021_05_43_36\configs\train_config.json
`
to `"DEVICE": "0,"`
