### ISSUE TITLE
what is dapalib?  I can't find any way to download library named dapalib

### ISSUE THREAD

**Issue by ransetid** [YxZhxn/Ray3D#19]
pip install -r requirements.txt
show me the errors as follow:
ERROR: Could not find a version that satisfies the requirement dapdalib (from versions: none)
ERROR: No matching distribution found for dapdalib

so I'd like to know which platform does this code run on ? Windows or Linux?
How did you download the dapalib library? I even can't find any useful information on Google

Thanks so much if I can get help from you.

**Comment by YxZhxn** [comment]
The code is running on Linux OS. A work around is to ignore that package. It is an optional installation. I cannot recall how I installed that dapalib any more.
