### ISSUE TITLE
Question about the camera parameters of the Human3.6M dataset

### ISSUE THREAD

**Issue by tinatiansjz** [YxZhxn/Ray3D#20]
Hi, thanks for your excellent work and open source~
I am little confused about the difference of the H36M's camera parameters provided by [this repo](https://github.com/YxZhxn/Ray3D/blob/main/data/camera_augmentation.py) and [VideoPose3D](https://github.com/facebookresearch/VideoPose3D/blob/main/common/h36m_dataset.py). Details are as follows.
1. `tangential_distortion` in the `h36m_cameras_intrinsic_params` seems to reverse left and right.
2. `R` and `translation` in the `h36m_cameras_extrinsic_params` are very different from VideoPose3D. I was wondering how to determine the rotation and translation of each camera and each subject.

Looking forward to your reply.

**Comment by tinatiansjz** [comment]
I figured out the 2nd sub-problem by myself :)

`R` and `translation` in [this repo](https://github.com/YxZhxn/Ray3D/blob/main/data/camera_augmentation.py) are `R_{W2C}` and `T_{W2C}`, respectively. Differently, `orientation` and `translation` in [VideoPose3D](https://github.com/facebookresearch/VideoPose3D/blob/main/common/h36m_dataset.py) are `R_{C2W}` and `T_{C2W}`, respectively.

**Comment by tinatiansjz** [comment]
I figured out the 1st sub-problem today~

`tangential_distortion` in [this repo](https://github.com/YxZhxn/Ray3D/blob/main/data/camera_augmentation.py#L45) is `[p1, p2]`, which instead in [VideoPose3D](https://github.com/facebookresearch/VideoPose3D/blob/main/common/h36m_dataset.py#L25) is `[p2, p1]`.

**Comment by YxZhxn** [comment]
Hi, sorry for my late response. You're right! We took all parameters from this repo [[human36m-camera-parameters](https://github.com/karfly/human36m-camera-parameters)](https://github.com/karfly/human36m-camera-parameters/blob/master/camera-parameters.json) for better visualization and anlysis.
