### ISSUE TITLE
can you provide a config and pretrained model of 1 frame

### ISSUE THREAD

**Issue by akk-123** [YxZhxn/Ray3D#5]
hi @YxZhxn, can you provide a config and pretrained model of 1 frame?

**Comment by YxZhxn** [comment]
Hi, you can launch 1-frame-model training by modifying the provided config files easily.

**Comment by akk-123** [comment]
hi, if a use this pretrain model, which config should I use?
![image](https://user-images.githubusercontent.com/98469560/161954076-54bed71c-0147-4573-8e18-5568496eed65.png)

and I shoud modifying the config like below?
```
'NUM_FRAMES': 1,

 'CAUSAL': True,
```

**Comment by YxZhxn** [comment]
You can checkout to 'poselifter' branch, and use the following config file https://github.com/YxZhxn/Ray3D/blob/poselifter/cfg/cfg_poselifter_3dhp.py . 
Please note that poselifter perfroms worse than other models on 3DHIP
