### ISSUE TITLE
2d keypoint npz for  test  videos

### ISSUE THREAD

**Issue by alecda573** [YxZhxn/Ray3D#6]
I have been doing  some visualization of overlaying the 2D keypoints on the test image sequences released in MPI and I am noticing that the keypoints appear to be sampled at a different rate than the test videos. For examples, TS1 has agreement up to around frame 700  and then the 2D poses skip ahead and remain that way for the rest of the sequence. Do you have any idea why this might be occurring?

**Comment by YxZhxn** [comment]
When I was using mpi_inf_3dhp dataset, I noticed that keypoints  saved in annot_data.mat are aligned with image sequence accurately. Sorry, I have no idea what is the cause to your question.

**Comment by alecda573** [comment]
@YxZhxn I agree the .mat files are what I didn’t make clear and I apologize is after I run the preprocessing without computing the normalized ray representation this discrepancy occurs and I’m curious if you did any visualization after running the preprocessing in this repo

**Comment by YxZhxn** [comment]
I did visualization with/without normalized ray representation, which was normal. Data prepocessing will not drop any data once reading from .npz files.

**Comment by YxZhxn** [comment]
Also, if you check the 3DHP 2D .npz file, you will find that 2D skeleton is attached with a string filename in it. You can use that information and do the visualization. Hope it helps you.
