### ISSUE TITLE
关于aggregate_camera

### ISSUE THREAD

**Issue by rixiaowo** [YxZhxn/Ray3D#7]
大佬我想问一下在aggregatec_camera.py文件中的Train/json，training.json，pitch/json文件是怎么生成的，我第一次接触不是很了解，我是直接下载了你提供的数据集。

**Comment by YxZhxn** [comment]
<img width="856" alt="Screen Shot 2022-04-15 at 14 49 45" src="https://user-images.githubusercontent.com/48275694/163532977-aa6d8151-9ad6-49cf-8813-99bece23116c.png">
首先参照这个步骤里的前两步, 你可以生成数据增强之后的相机参数文件和对应的文件夹; 然后将这些文件夹的路径填写在步骤3代码里的对应变量上, 运行之后可以得到用来训练和测试的Human3.6M增强数据集. 其他三个公开数据集的使用条件不依赖于这个数据集.

**Comment by rixiaowo** [comment]
谢谢大佬，已经弄好了，那你在Readme里面的步骤是有错误的/(ㄒoㄒ)/

**Comment by YxZhxn** [comment]
对, README里面的步骤2写错了. 现在已经更新了
