### ISSUE TITLE
Hope can provide a guide on how to test on custom data

### ISSUE THREAD

**Issue by visonpon** [YxZhxn/Ray3D#8]

**Comment by YxZhxn** [comment]
To test on custom data, you can follow this [tutorial](https://github.com/facebookresearch/VideoPose3D/issues/2#issuecomment-443502874) to create one custom dataset class which is similar as [Human36mDataset](https://github.com/YxZhxn/Ray3D/blob/490f63848e3a88ff86ab4eb62a6434b7b981f077/lib/dataset/h36m_dataset.py#L349). Also, you need to provide the camera intrinsics and extrinsics.
