### ISSUE TITLE
Can you please provide the code of inference the video in the wild?

### ISSUE THREAD

**Issue by lovelyfrog** [YxZhxn/Ray3D#9]
Can you please provide the code of inference the video in the wild?

**Comment by YxZhxn** [comment]
Generally speaking, our Ray3D isn't suitable for in-the-wild scenario. For the reason that you have to inject camera intrinsic and extrinsic parameters into the model. If you can perform calibration for the images that you collect from the scenario, you can follow my answer presented in issue #8 to construct a custom dataset and then perform inference.
